# SPDX-License-Identifier: CECILL-2.1
# Copyright (c) 2026 ESRF - the European Synchrotron

"""
The s4 numerical-mesh phase deflector (optical element and beamline element).

Follows the same pattern as the other ``s4_numerical_mesh_*`` elements (e.g.
:class:`~shadow4.beamline.optical_elements.refractors.s4_numerical_mesh_interface.S4NumericalMeshInterface`):
mixes the generic material/physics base
(:class:`~shadow4.beamline.optical_elements.phase_deflectors.s4_phase_deflector.S4PhaseDeflector`)
with ``S4NumericalMeshOpticalElementDecorator`` for the surface (here, the
projected-thickness) mesh, and implements :meth:`S4PhaseDeflector.get_thickness_map`
from it.

Unlike ``S4NumericalMeshInterface``, only a file source is accepted for the
mesh (no ``xx``/``yy``/``zz`` arrays): passing arrays directly cannot be
recovered by ``to_python_code()``, so the constructor only takes
``surface_data_file``.

This element reproduces the numerical-mesh thin-transmission element
previously implemented as ``S4ThinTransmission`` in
``shadow4.beamline.optical_elements.refractors.s4_thin_element`` (which
inherited ``S4Interface`` and used a Snell's-law refraction step): same
mesh loading/scaling/inversion, same optical constants, same ray-tracing
result, but built on the ``S4PhaseDeflector`` family instead of the
refractors family.
"""
from __future__ import annotations

import numpy

from syned.beamline.element_coordinates import ElementCoordinates

from shadow4.beam.s4_beam import S4Beam
from shadow4.beamline.s4_beamline_element_movements import S4BeamlineElementMovements
from shadow4.beamline.s4_optical_element_decorators import S4NumericalMeshOpticalElementDecorator
from shadow4.beamline.optical_elements.phase_deflectors.s4_phase_deflector import (
    S4PhaseDeflector,
    S4PhaseDeflectorElement,
)


class S4NumericalMeshPhaseDeflector(S4PhaseDeflector, S4NumericalMeshOpticalElementDecorator):
    """
    Shadow4 numerical-mesh phase deflector.

    Constructor.

    Parameters
    ----------
    name : str, optional
        The name of the element.
    boundary_shape : instance of BoundaryShape, optional
        The boundary shape of the element.
    surface_data_file : str, optional
        File (HDF5, or 3-column ASCII) with the projected-thickness mesh, in
        the standard OASYS surface convention. This is the only supported
        mesh source (see module docstring).
    material : str, optional
        String with the material element symbol or compound formula (used
        when ``f_r_ind`` is 2 or 3).
    density : float, optional
        The material density in g/cm^3 (used when ``f_r_ind`` is 2 or 3).
    f_r_ind : int, optional
        Source of the optical constants: 0=constant, 1=file (PREREFL
        preprocessor), 2=xraylib, 3=dabax.
    r_ind : float, optional
        For ``f_r_ind=0``: the real part of the refraction index.
    r_attenuation : float, optional
        For ``f_r_ind=0``: the attenuation coefficient, in m^-1.
    file_r_ind : str, optional
        For ``f_r_ind=1``: file generated by the PREREFL preprocessor.
    dabax : None or instance of DabaxXraylib, optional
        The pointer to the dabax library (used for ``f_r_ind=3``).
    apply_to_lost : bool, optional
        Default for ``trace_beam``'s ``apply_to_lost`` parameter (may be
        overridden per call): if True, apply the phase deflection to rays
        already marked lost before this element too, as long as they land on
        valid thickness support; their negative flag is preserved.
    shift_thickness_to_zero : bool, optional
        If True, subtract the finite minimum from the thickness profile
        (after scaling/inversion) so it is non-negative everywhere.
    thickness_scaling : float, optional
        Scale factor applied to the thickness profile.
    coordinate_scaling : float, optional
        Scale factor applied to the mesh's X and Y axes. Must be finite and
        strictly positive.
    invert_surface : bool, optional
        If True, negate the thickness profile (after scaling) before the
        (optional) zero-shift.

    Returns
    -------
    instance of S4NumericalMeshPhaseDeflector.
    """
    def __init__(self,
                 name="Undefined",
                 boundary_shape=None,
                 surface_data_file=None,
                 material="",
                 density=1.0,
                 f_r_ind=0,
                 r_ind=1.0,
                 r_attenuation=0.0,
                 file_r_ind="",
                 dabax=None,
                 apply_to_lost=True,
                 shift_thickness_to_zero=False,
                 thickness_scaling=1.0,
                 coordinate_scaling=1.0,
                 invert_surface=False,
                 ):
        S4NumericalMeshOpticalElementDecorator.__init__(self, xx=None, yy=None, zz=None,
                                                         surface_data_file=surface_data_file)
        S4PhaseDeflector.__init__(self,
                                  name=name,
                                  boundary_shape=boundary_shape,
                                  surface_shape=self.get_surface_shape_instance(),
                                  material=material,
                                  density=density,
                                  f_r_ind=f_r_ind,
                                  r_ind=r_ind,
                                  r_attenuation=r_attenuation,
                                  file_r_ind=file_r_ind,
                                  dabax=dabax,
                                  )

        if not numpy.isfinite(thickness_scaling):
            raise ValueError("thickness_scaling must be finite.")
        if not numpy.isfinite(coordinate_scaling) or coordinate_scaling <= 0.0:
            raise ValueError("coordinate_scaling must be finite and strictly positive.")

        self._surface_data_file = surface_data_file
        self._apply_to_lost = apply_to_lost
        self._shift_thickness_to_zero = shift_thickness_to_zero
        self._thickness_scaling = float(thickness_scaling)
        self._coordinate_scaling = float(coordinate_scaling)
        self._invert_surface = bool(invert_surface)

        # support text containing name of variable, help text and unit. Will be stored in self._support_dictionary
        # NOTE: "surface_data_file" is also stored as a plain attribute (self._surface_data_file) above,
        # duplicating what S4NumericalMeshOpticalElementDecorator already keeps inside the NumericalMesh
        # surface_shape -- required because syned's to_dictionary()/to_json() resolve each registered key
        # via eval("self._<key>"), not through get_surface_shape_instance().
        self._add_support_text([
                    ("surface_data_file",       "File with the thickness mesh (HDF5 or 3-column ASCII)", ""),
                    ("apply_to_lost",           "Apply the phase deflection to already-lost rays too",   ""),
                    ("shift_thickness_to_zero", "Shift the thickness profile so its minimum is zero",    ""),
                    ("thickness_scaling",       "Scale factor applied to the thickness profile",         ""),
                    ("coordinate_scaling",      "Scale factor applied to the mesh X/Y axes",              ""),
                    ("invert_surface",          "Invert (negate) the thickness profile",                  ""),
            ] )

        self.__inputs = {
            "name": name,
            "boundary_shape": boundary_shape,
            "surface_data_file": surface_data_file,
            "material": material,
            "density": density,
            "f_r_ind": f_r_ind,
            "r_ind": r_ind,
            "r_attenuation": r_attenuation,
            "file_r_ind": file_r_ind,
            "dabax": self._get_dabax_txt(),
            "apply_to_lost": apply_to_lost,
            "shift_thickness_to_zero": shift_thickness_to_zero,
            "thickness_scaling": thickness_scaling,
            "coordinate_scaling": coordinate_scaling,
            "invert_surface": invert_surface,
        }

    def get_info(self):
        """
        Returns the specific information of the S4 numerical-mesh phase
        deflector optical element.

        Returns
        -------
        str
        """
        txt = super().get_info()
        txt += "  apply_to_lost: %s\n" % self._apply_to_lost
        txt += "  shift_thickness_to_zero: %s\n" % self._shift_thickness_to_zero
        txt += "  Thickness scaling: %g\n" % self._thickness_scaling
        txt += "  Coordinate scaling: %g\n" % self._coordinate_scaling
        txt += "  Invert surface: %s\n" % self._invert_surface

        thickness_mesh = self.get_surface_shape_instance()
        if thickness_mesh is not None and thickness_mesh.has_surface_data_file():
            txt += "  Thickness data file: %s\n" % thickness_mesh._surface_data_file
        else:
            txt += "  Thickness data: undefined\n"
        return txt

    def get_thickness_map(self, validate=True):
        """
        Return the internal thickness dictionary used by the numerical kernel.

        Set ``validate=False`` to inspect the transformed map without rejecting
        negative values. This is intended for previews; tracing always uses the
        validated default.
        """
        thickness_mesh = self.get_surface_shape_instance()
        if thickness_mesh is None or not thickness_mesh.has_surface_data_file():
            raise ValueError("No surface_data_file supplied.")

        mesh = self.get_optical_surface_instance()
        x_axis, y_axis = mesh.get_mesh_x_y()
        # S4Mesh stores its z grid as (len(x_axis), len(y_axis)); the phase-
        # deflection kernel (and numpy.gradient(profile, y_axis, x_axis))
        # expects the transposed (len(y_axis), len(x_axis)) convention.
        profile = mesh.get_mesh_z().T

        x_axis = numpy.asarray(x_axis, dtype=float) * self._coordinate_scaling
        y_axis = numpy.asarray(y_axis, dtype=float) * self._coordinate_scaling
        profile = numpy.asarray(profile, dtype=float) * self._thickness_scaling
        if self._invert_surface:
            profile = -profile

        if self._shift_thickness_to_zero:
            finite = numpy.isfinite(profile)
            if numpy.any(finite):
                profile = profile - numpy.nanmin(profile)
        elif validate and numpy.any(profile[numpy.isfinite(profile)] < 0.0):
            raise ValueError(
                "Thickness profile contains negative values. Use "
                "shift_thickness_to_zero=True to subtract the finite minimum."
            )

        return {
            "profile": profile,
            "x_axis": x_axis,
            "y_axis": y_axis,
        }

    def to_python_code(self, **kwargs):
        """
        Creates the python code for defining the element.

        Parameters
        ----------
        **kwargs

        Returns
        -------
        str
            Python code.
        """
        txt = self.to_python_code_boundary_shape()
        txt += "\nfrom shadow4.beamline.optical_elements.phase_deflectors.s4_numerical_mesh_phase_deflector import S4NumericalMeshPhaseDeflector"
        txt += "\noptical_element = S4NumericalMeshPhaseDeflector(name='%s', boundary_shape=boundary_shape," % self.__inputs["name"]
        txt += "\n    surface_data_file=%r," % self.__inputs["surface_data_file"]
        txt += "\n    material='%s', density=%g," % (self.__inputs["material"], self.__inputs["density"])
        txt += "\n    f_r_ind=%d, # 0=constant, 1=file, 2=xraylib, 3=dabax" % self.__inputs["f_r_ind"]
        txt += "\n    file_r_ind=%r," % self.__inputs["file_r_ind"]
        txt += "\n    r_ind=%.10g," % self.__inputs["r_ind"]
        txt += "\n    r_attenuation=%g," % self.__inputs["r_attenuation"]
        txt += "\n    dabax=%s," % self.__inputs["dabax"]
        txt += "\n    apply_to_lost=%s," % repr(self.__inputs["apply_to_lost"])
        txt += "\n    shift_thickness_to_zero=%s," % repr(self.__inputs["shift_thickness_to_zero"])
        txt += "\n    thickness_scaling=%g," % self.__inputs["thickness_scaling"]
        txt += "\n    coordinate_scaling=%g," % self.__inputs["coordinate_scaling"]
        txt += "\n    invert_surface=%s," % repr(self.__inputs["invert_surface"])
        txt += "\n    )"
        return txt


class S4NumericalMeshPhaseDeflectorElement(S4PhaseDeflectorElement):
    """
    Shadow4 beamline element wrapper for :class:`S4NumericalMeshPhaseDeflector`.

    Parameters
    ----------
    optical_element : instance of S4NumericalMeshPhaseDeflector, optional
        The shadow4 optical element.
    coordinates : instance of ElementCoordinates, optional
        The syned element coordinates.
    movements : instance of S4BeamlineElementMovements, optional
        The S4 element movements.
    input_beam : instance of S4Beam, optional
        The S4 incident beam.

    Returns
    -------
    instance of S4NumericalMeshPhaseDeflectorElement.
    """
    def __init__(self,
                 optical_element: S4NumericalMeshPhaseDeflector = None,
                 coordinates: ElementCoordinates = None,
                 movements: S4BeamlineElementMovements = None,
                 input_beam: S4Beam = None):
        super().__init__(optical_element=optical_element if optical_element is not None else S4NumericalMeshPhaseDeflector(),
                         coordinates=coordinates if coordinates is not None else ElementCoordinates(),
                         movements=movements,
                         input_beam=input_beam)

    def trace_beam(self, **params):
        """
        Runs (ray tracing) the input beam through the element.

        Same as :meth:`S4PhaseDeflectorElement.trace_beam`, except that
        ``apply_to_lost``, if not explicitly given in ``**params``, defaults
        to the optical element's own persisted ``apply_to_lost`` setting
        (matching the old ``S4ThinTransmission``'s behavior) rather than
        unconditionally to True.

        Parameters
        ----------
        **params

        Returns
        -------
        tuple
            (output_beam, footprint) instances of S4Beam.
        """
        params.setdefault("apply_to_lost", self.get_optical_element()._apply_to_lost)
        return super().trace_beam(**params)

    def to_python_code(self, **kwargs):
        """
        Creates the python code for defining the element.

        Parameters
        ----------
        **kwargs

        Returns
        -------
        str
            Python code.
        """
        txt = "\n\n# optical element number XX"
        txt += self.get_optical_element().to_python_code()
        txt += self.to_python_code_coordinates()
        txt += self.to_python_code_movements()
        txt += "\nfrom shadow4.beamline.optical_elements.phase_deflectors.s4_numerical_mesh_phase_deflector import S4NumericalMeshPhaseDeflectorElement"
        txt += "\nbeamline_element = S4NumericalMeshPhaseDeflectorElement(optical_element=optical_element, coordinates=coordinates, movements=movements, input_beam=beam)"
        txt += "\n\nbeam, footprint = beamline_element.trace_beam()"
        return txt


if __name__ == "__main__":
    import numpy as np
    from dabax.dabax_xraylib import DabaxXraylib
    from shadow4.beamline.s4_beamline import S4Beamline

    beamline = S4Beamline()

    from shadow4.sources.source_geometrical.source_geometrical import SourceGeometrical

    light_source = SourceGeometrical(name='Geometrical Source', nrays=5000, seed=5676561)
    light_source.set_spatial_type_point()
    light_source.set_depth_distribution_off()
    light_source.set_angular_distribution_gaussian(sigdix=1e-05, sigdiz=1e-05)
    light_source.set_energy_distribution_uniform(value_min=9950, value_max=10050, unit='eV')
    light_source.set_polarization(polarization_degree=1, phase_diff=0, coherent_beam=0)
    beam = light_source.get_beam()

    beamline.set_light_source(light_source)

    # optical element number XX
    boundary_shape = None

    optical_element = S4NumericalMeshPhaseDeflector(
        name='Phase Deflector', boundary_shape=boundary_shape,
        surface_data_file='/home/srio/Oasys2/lens_interface_1.h5',
        material='Be', density=1.85,
        f_r_ind=3,  # 0=constant, 1=file, 2=xraylib, 3=dabax
        r_ind=1,
        r_attenuation=0,
        dabax=DabaxXraylib(file_f1f2="f1f2_Windt.dat", file_CrossSec="CrossSec_EPDL97.dat"),
        apply_to_lost=True,
        shift_thickness_to_zero=False,
        thickness_scaling=1,
        coordinate_scaling=1,
        invert_surface=False,
    )

    coordinates = ElementCoordinates(p=10, q=0, angle_radial=0, angle_azimuthal=0, angle_radial_out=3.141592654)
    movements = None
    beamline_element = S4NumericalMeshPhaseDeflectorElement(
        optical_element=optical_element, coordinates=coordinates, movements=movements, input_beam=beam,
    )

    beam, footprint = beamline_element.trace_beam()

    beamline.append_beamline_element(beamline_element)

    if True:
        from srxraylib.plot.gol import plot_scatter
        plot_scatter(1e6 * beam.get_column(1, nolost=1), 1e6 * beam.get_column(3, nolost=1), title='(X,Z) in microns')

    print(optical_element.info())
    print(optical_element.get_info())

    print(beamline.to_json())
