# SPDX-License-Identifier: CECILL-2.1
# Copyright (c) 2026 ESRF - the European Synchrotron

"""
Shadow4 phase-deflector base class and numerical kernel.

A phase deflector is a thin, normal-incidence-only optical element that
deflects, attenuates and dephases a beam through the local gradient of the
optical path difference (OPD) introduced by a spatially-varying material
thickness -- as opposed to :class:`~shadow4.beamline.optical_elements.refractors.s4_interface.S4Interface`,
which models a real interface between two materials and refracts the beam
via Snell's law at a (possibly curved) surface intersection.

Consequences of that distinction:

- A phase deflector has a single material (surrounded by vacuum on both
  sides), not an object-side/image-side pair: there is nothing on "the
  other side" of a thin slab to refract into.
- There is no ray/surface intersection to solve for: the element is always
  flat and at normal incidence, so a ray reaching it is simply advanced to
  the element's plane, and the local thickness map is sampled there.

``S4PhaseDeflector`` provides the material/optical-constant side only, and
leaves the thickness map itself abstract (:meth:`S4PhaseDeflector.get_thickness_map`):
a concrete element mixes this class with a surface-shape decorator (e.g.
``S4NumericalMeshOpticalElementDecorator`` for a projected-thickness-map
element read from a file) and implements ``get_thickness_map()`` from it,
the same way ``S4Interface`` is mixed with a surface-shape decorator and
relies on it for ``get_optical_surface_instance()``.
"""
from __future__ import annotations

import numpy
from numpy.typing import ArrayLike

from syned.beamline.element_coordinates import ElementCoordinates
from syned.beamline.optical_element_with_surface_shape import OpticalElementsWithSurfaceShape
from syned.beamline.shape import Ellipse, Rectangle

from dabax.dabax_xraylib import DabaxXraylib

from shadow4.beam.s4_beam import S4Beam
from shadow4.beamline.s4_beamline_element import S4BeamlineElement
from shadow4.beamline.s4_beamline_element_movements import S4BeamlineElementMovements
from shadow4.beamline.s4_optical_element_decorators import S4OpticalElementDecorator
from shadow4.physical_models.prerefl.prerefl import PreRefl


class S4PhaseDeflector(OpticalElementsWithSurfaceShape, S4OpticalElementDecorator):
    """
    Shadow4 phase-deflector base class.

    This is a base class (analogous to ``S4Interface`` for refractive
    interfaces): it defines the single-material optical constants, but
    leaves the thickness map abstract. Use a derived/mixed-in class (e.g.
    combining this with ``S4NumericalMeshOpticalElementDecorator``) to
    provide :meth:`get_thickness_map`.

    Parameters
    ----------
    name : str, optional
        The name of the element.
    boundary_shape : instance of BoundaryShape, optional
        The boundary shape of the element.
    surface_shape : instance of SurfaceShape, optional
        The (thickness) surface shape of the element, normally supplied by
        the mixed-in surface-shape decorator.
    material : str, optional
        String with the material element symbol or compound formula (used
        when ``f_r_ind`` is 2 or 3).
    density : float, optional
        The material density in g/cm^3 (used when ``f_r_ind`` is 2 or 3).
    f_r_ind : int, optional
        Source of the optical constants:
            - (0) constant value,
            - (1) file generated by the PREREFL preprocessor,
            - (2) direct calculation using xraylib,
            - (3) direct calculation using dabax.
    r_ind : float, optional
        For ``f_r_ind=0``: the real part of the refraction index.
    r_attenuation : float, optional
        For ``f_r_ind=0``: the attenuation coefficient, in m^-1.
    file_r_ind : str, optional
        For ``f_r_ind=1``: file generated by the PREREFL preprocessor.
    dabax : None or instance of DabaxXraylib, optional
        The pointer to the dabax library (used for ``f_r_ind=3``).

    Returns
    -------
    instance of S4PhaseDeflector.
    """
    def __init__(self,
                 name="Undefined",
                 boundary_shape=None,
                 surface_shape=None,
                 material="",
                 density=1.0,
                 f_r_ind=0,
                 r_ind=1.0,
                 r_attenuation=0.0,
                 file_r_ind="",
                 dabax=None,
                 ):
        OpticalElementsWithSurfaceShape.__init__(self,
                                                 name=name,
                                                 surface_shape=surface_shape,
                                                 boundary_shape=boundary_shape,
                                                 )

        if f_r_ind not in (0, 1, 2, 3):
            raise ValueError("f_r_ind must be 0, 1, 2 or 3.")

        self._material = material
        self._density = density
        self._f_r_ind = f_r_ind
        self._r_ind = r_ind
        self._r_attenuation = r_attenuation
        self._file_r_ind = file_r_ind
        self._dabax = dabax

        # support text containing name of variable, help text and unit. Will be stored in self._support_dictionary
        # NOTE: "dabax" is deliberately NOT registered here, matching S4Interface/S4CRL/S4Lens: once a
        # DabaxXraylib instance has been used (e.g. by get_optical_constants()), it caches an internal
        # SpecFile object that syned's generic to_dictionary()/to_json() cannot serialize.
        self._add_support_text([
                    ("surface_shape",   "Surface (thickness) shape",                                     ""),
                    ("material",        "Material (element, compound, name or refraction index)",        ""),
                    ("density",         "Density",                                                       "g/cm3"),
                    ("f_r_ind",         "Source of optical constants: 0=constant, 1=file, 2=xraylib, 3=dabax", ""),
                    ("r_ind",           "Refraction index (real part), for f_r_ind=0",                    ""),
                    ("r_attenuation",   "Attenuation coefficient, for f_r_ind=0",                         "m^-1"),
                    ("file_r_ind",      "File generated by the PREREFL preprocessor, for f_r_ind=1",      ""),
            ] )

    def get_info(self):
        """
        Returns the specific information of the S4 phase-deflector optical
        element.

        Returns
        -------
        str
        """
        txt = "\n\n"
        txt += "PHASE DEFLECTOR\n"
        txt += "\n"
        txt += "Source of material refraction index:\n"
        if self._f_r_ind == 0:
            txt += "   constant value\n"
            txt += "   index of refraction (real part): %g \n" % self._r_ind
            txt += "   attenuation coefficient: %g m^-1\n" % self._r_attenuation
        elif self._f_r_ind == 1:
            txt += "   file generated by prerefl preprocessor: %s \n" % self._file_r_ind
        elif self._f_r_ind == 2:
            txt += "   calculated using xraylib\n"
            txt += "       material: %s\n" % self._material
            txt += "       density: %g g/cm3\n" % self._density
        elif self._f_r_ind == 3:
            txt += "   calculated using dabax\n"
            txt += "       material: %s\n" % self._material
            txt += "       density: %g g/cm3\n" % self._density

        txt += "\n"
        ss = self.get_surface_shape()
        if ss is None:
            txt += "Surface shape is: Plane (** UNDEFINED?? **)\n"
        else:
            txt += "Surface shape is: %s\n" % ss.__class__.__name__

        boundary = self.get_boundary_shape()
        if boundary is None:
            txt += "Surface boundaries not considered (infinite)\n"
        else:
            txt += "Surface boundaries are: %s\n" % boundary.__class__.__name__
            txt += "    Limits: " + repr(boundary.get_boundaries()) + "\n"

        return txt

    def get_thickness_map(self, validate=True):
        """
        Returns the local projected-thickness map used by the phase-gradient
        kernel.

        Parameters
        ----------
        validate : bool, optional
            Set False to inspect the map without rejecting negative values
            (intended for previews); tracing always uses the validated
            default.

        Returns
        -------
        dict
            Dictionary with keys ``"profile"`` (2D array, shape ``(ny, nx)``,
            in metres), ``"x_axis"`` and ``"y_axis"`` (1D arrays sampling the
            element's local transverse X and Y axes, in metres).

        Raises
        ------
        NotImplementedError
            This base class does not know how the thickness is represented
            (mesh, analytic, ...); a concrete subclass (or a mixed-in
            surface-shape decorator) must provide it.
        """
        raise NotImplementedError()

    def get_refraction_index(self, photon_energy_eV=None):
        """
        Returns the real part of the refraction index.

        Parameters
        ----------
        photon_energy_eV : float or numpy array, optional
            The photon energy in eV.

        Returns
        -------
        float or numpy array
        """
        if self._f_r_ind == 0:
            return self._r_ind
        elif self._f_r_ind == 1:
            pr = PreRefl()
            pr.read_preprocessor_file(self._file_r_ind)
            return pr.get_refraction_index(photon_energy_eV).real
        elif self._f_r_ind == 2:
            return PreRefl.get_refraction_index_real_external_xraylib(
                material=self._material, photon_energy_ev=photon_energy_eV, density=self._density,
            )
        elif self._f_r_ind == 3:
            return PreRefl.get_refraction_index_real_external_dabax(
                material=self._material, photon_energy_ev=photon_energy_eV, density=self._density,
                dabax=self._dabax,
            )
        raise ValueError("f_r_ind must be 0, 1, 2 or 3.")

    def get_attenuation_coefficient(self, photon_energy_eV=None):
        """
        Returns the attenuation coefficient.

        Parameters
        ----------
        photon_energy_eV : float or numpy array, optional
            The photon energy in eV.

        Returns
        -------
        float or numpy array
            The attenuation coefficient, in m^-1.
        """
        if self._f_r_ind == 0:
            return self._r_attenuation
        elif self._f_r_ind == 1:
            pr = PreRefl()
            pr.read_preprocessor_file(self._file_r_ind)
            return pr.get_attenuation_coefficient(photon_energy_eV) * 100.0  # cm^-1 -> m^-1
        elif self._f_r_ind == 2:
            return PreRefl.get_attenuation_coefficient_external_xraylib(
                photon_energy_ev=photon_energy_eV, material=self._material, density=self._density,
            ) * 100.0
        elif self._f_r_ind == 3:
            return PreRefl.get_attenuation_coefficient_external_dabax(
                photon_energy_ev=photon_energy_eV, material=self._material, density=self._density,
                dabax=self._dabax,
            ) * 100.0
        raise ValueError("f_r_ind must be 0, 1, 2 or 3.")

    def get_optical_constants(self, photon_energy_eV, k):
        """
        Returns per-ray ``delta`` and ``beta``, with ``n = 1 - delta + 1j * beta``.

        Parameters
        ----------
        photon_energy_eV : float or numpy array
            The photon energy in eV.
        k : float or numpy array
            The vacuum wavenumber, ``2*pi/wavelength``, in m^-1.

        Returns
        -------
        tuple
            (delta, beta)
        """
        n_real = numpy.asarray(self.get_refraction_index(photon_energy_eV), dtype=float)
        mu = numpy.asarray(self.get_attenuation_coefficient(photon_energy_eV), dtype=float)
        delta = 1.0 - n_real
        beta = mu / (2.0 * numpy.asarray(k, dtype=float))
        return delta, beta

    def to_python_code(self, **kwargs):
        """
        Creates the python code for defining the element.

        Raises
        ------
        NotImplementedError.
        """
        raise NotImplementedError("To be implemented in the children class")

    def to_python_code_boundary_shape(self):
        """
        Creates a code block with information of boundary shape.

        Returns
        -------
        str
            The text with the code.
        """
        txt = ""
        bs = self._boundary_shape
        if bs is None:
            txt += "\nboundary_shape = None"
        elif isinstance(bs, Rectangle):
            txt += "\nfrom syned.beamline.shape import Rectangle"
            txt += "\nboundary_shape = Rectangle(x_left=%g, x_right=%g, y_bottom=%g, y_top=%g)" % bs.get_boundaries()
        elif isinstance(bs, Ellipse):
            txt += "\nfrom syned.beamline.shape import Ellipse"
            txt += "\nboundary_shape = Ellipse(a_axis_min=%g, a_axis_max=%g, b_axis_min=%g, b_axis_max=%g)" % bs.get_boundaries()
        else:
            txt += "\nboundary_shape = None"
        return txt

    def _get_dabax_txt(self):
        if self._f_r_ind == 3:
            if isinstance(self._dabax, DabaxXraylib):
                return 'DabaxXraylib(file_f1f2="%s", file_CrossSec="%s")' % (
                    self._dabax.get_file_f1f2(), self._dabax.get_file_CrossSec(),
                )
            return "DabaxXraylib()"
        return "None"


class S4PhaseDeflectorElement(S4BeamlineElement):
    """
    Shadow4 beamline element wrapper for :class:`S4PhaseDeflector` subclasses.

    Follows the same ``trace_beam`` structure as
    :class:`~shadow4.beamline.optical_elements.refractors.s4_interface.S4InterfaceElement`
    (put the beam in the element reference system, apply the element's
    physics, apply boundaries, transform back to the image plane); the
    Snell's-law refraction step (``_apply_interface_refraction``) is
    replaced by :meth:`_apply_phase_deflection`.

    Parameters
    ----------
    optical_element : instance of S4PhaseDeflector, optional
        The shadow4 optical element.
    coordinates : instance of ElementCoordinates, optional
        The syned element coordinates.
    movements : instance of S4BeamlineElementMovements, optional
        The S4 element movements.
    input_beam : instance of S4Beam, optional
        The S4 incident beam.

    Returns
    -------
    instance of S4PhaseDeflectorElement.
    """
    def __init__(self,
                 optical_element: S4PhaseDeflector = None,
                 coordinates: ElementCoordinates = None,
                 movements: S4BeamlineElementMovements = None,
                 input_beam: S4Beam = None):
        super().__init__(optical_element=optical_element if optical_element is not None else S4PhaseDeflector(),
                         coordinates=coordinates if coordinates is not None else ElementCoordinates(),
                         movements=movements,
                         input_beam=input_beam)
        self.__stored_optical_constants = None

    def get_stored_optical_constants(self):
        """
        When running ``trace_beam()`` the optical constants (delta, beta)
        are calculated. They are stored for accelerating further calls.

        Returns
        -------
        tuple
            (delta, beta), arrays with the refractive index decrement and
            the absorption index, one value per ray.
        """
        return self.__stored_optical_constants

    def _apply_phase_deflection(self, beam, delta, beta, *, flag_lost_value=-1.0, apply_to_lost=True):
        """
        Apply the phase-gradient deflection to a beam already expressed in
        the element's local reference frame.

        This plays the same role as ``S4Interface._apply_interface_refraction``
        (called the same way, from :meth:`trace_beam`, right after the beam
        has been put into the element reference system), but instead of a
        Snell's-law ray/surface intersection it advances each ray to the
        flat element plane (Z=0) and then applies the local thickness map's
        attenuation, OPD/phase and phase-gradient kicks (see
        :func:`apply_phase_deflection`). Kept here (on the beamline element,
        not on ``S4PhaseDeflector``) since everything it needs -- the
        optical element and the beam already in the local frame -- is
        already local to :meth:`trace_beam`.
        """
        soe = self.get_optical_element()
        k = beam.get_column(11) * 100.0
        _advance_rays_to_local_surface(beam)
        return apply_phase_deflection(
            beam,
            soe.get_thickness_map(),
            k,
            delta,
            beta,
            flag_lost_value=flag_lost_value,
            apply_to_lost=apply_to_lost,
            duplicate=False,
        )

    def trace_beam(self, **params):
        """
        Runs (ray tracing) the input beam through the element.

        Parameters
        ----------
        **params
            ``flag_lost_value`` (default -1.0), ``apply_to_lost`` (default
            True), ``reused_stored_optical_constants`` (default None),
            ``angle_tolerance`` (default 1e-9).

        Returns
        -------
        tuple
            (output_beam, footprint) instances of S4Beam.
        """
        flag_lost_value = params.get("flag_lost_value", -1.0)
        apply_to_lost = params.get("apply_to_lost", True)
        reused_stored_optical_constants = params.get("reused_stored_optical_constants", None)
        angle_tolerance = params.get("angle_tolerance", 1e-9)

        p = self.get_coordinates().p()
        q = self.get_coordinates().q()
        angle_radial = self.get_coordinates().angle_radial()
        angle_radial_out = self.get_coordinates().angle_radial_out()
        alpha1 = self.get_coordinates().angle_azimuthal()

        if not numpy.isclose(angle_radial, 0.0, rtol=0.0, atol=angle_tolerance):
            raise NotImplementedError("S4PhaseDeflector supports only angle_radial=0.")
        if not numpy.isclose(angle_radial_out, numpy.pi, rtol=0.0, atol=angle_tolerance):
            raise NotImplementedError("S4PhaseDeflector supports only angle_radial_out=pi.")
        if not numpy.isclose(alpha1, 0.0, rtol=0.0, atol=angle_tolerance):
            raise NotImplementedError("S4PhaseDeflector angle_azimuthal rotations are not implemented yet.")

        theta_grazing1 = numpy.pi / 2 - angle_radial
        theta_grazing2 = numpy.pi / 2 - angle_radial_out

        #
        input_beam = self.get_input_beam().duplicate()
        soe = self.get_optical_element()

        # retrieve and store optical constants
        if reused_stored_optical_constants is not None:
            delta, beta = reused_stored_optical_constants
        else:
            energy1 = input_beam.get_photon_energy_eV()
            k1 = input_beam.get_column(11) * 100.0
            delta, beta = soe.get_optical_constants(energy1, k1)
            self.__stored_optical_constants = (delta, beta)

        #
        # put beam in element reference system
        #
        input_beam.rotate(alpha1, axis=2)
        input_beam.rotate(theta_grazing1, axis=1)
        input_beam.translation([0.0, -p * numpy.cos(theta_grazing1), p * numpy.sin(theta_grazing1)])

        # element movement:
        movements = self.get_movements()
        if movements is not None:
            if movements.f_move:
                raise NotImplementedError("S4PhaseDeflector movements are not implemented yet.")

        #
        # apply the phase-gradient deflection
        #
        footprint = self._apply_phase_deflection(
            input_beam, delta, beta,
            flag_lost_value=flag_lost_value,
            apply_to_lost=apply_to_lost,
        )

        #
        # apply element boundaries
        #
        footprint.apply_boundaries_syned(soe.get_boundary_shape(), flag_lost_value=flag_lost_value)

        #
        # from element reference system to image plane
        #
        output_beam = footprint.duplicate()
        output_beam.change_to_image_reference_system(theta_grazing2, q, refraction_index=1.0, apply_attenuation=0)

        return output_beam, footprint

    def to_python_code(self, **kwargs):
        """
        Creates the python code for defining the element.

        Raises
        ------
        NotImplementedError.
        """
        raise NotImplementedError("To be implemented in the children class")


def _advance_rays_to_local_surface(beam: S4Beam) -> None:
    """
    Propagate every ray, in place and using its own direction, from its
    current position in the element's local reference frame to the flat
    element plane at Z=0 (column 3), accumulating the traversed distance
    into the optical path length (column 13).

    This is the flat-plane analogue of the ray/surface intersection that
    ``S4Mesh.apply_refraction_on_beam`` performs for curved interfaces inside
    ``S4Interface._apply_interface_refraction``: after the
    ``S4InterfaceElement``-style rotate/translate, every ray starts at local
    Z = p (the source-to-element distance) and travels in -Z; this brings it
    to Z = 0 so :func:`apply_phase_deflection` can interpolate the thickness
    map at the ray's actual (possibly divergence-shifted) position.
    """
    rays = beam.rays
    tof = -rays[:, 2] / rays[:, 5]
    rays[:, 0] += tof * rays[:, 3]
    rays[:, 1] += tof * rays[:, 4]
    rays[:, 2] += tof * rays[:, 5]
    rays[:, 12] += tof


def apply_phase_deflection(
    beam: S4Beam,
    thickness: dict,
    k: ArrayLike,
    delta: ArrayLike,
    beta: ArrayLike,
    *,
    flag_lost_value: float = -1.0,
    apply_to_lost: bool = True,
    duplicate: bool = True,
) -> S4Beam:
    """
    Apply a thin phase-deflector's projected-thickness kick to a beam
    already expressed in the element's local reference frame, i.e. after the
    same "put beam in element reference system" transform that
    ``S4InterfaceElement.trace_beam`` applies before refraction: the
    transverse plane is (X, Y) [columns 1, 2] and the beam travels along
    -Z [column 3], reaching the (flat) element at Z=0.

    Parameters
    ----------
    beam : shadow4.beam.s4_beam.S4Beam
        Beam in the element's local reference frame. Columns 1 and 2 (X, Y)
        are not changed; column 3 (Z) is expected to be (numerically) zero
        for rays landing on the element.
    thickness : dict
        Dictionary with keys ``"profile"``, ``"x_axis"`` and ``"y_axis"``.
        ``profile`` is a 2D array ``profile[y, x]`` containing the projected
        thickness in meters, sampled on the element's local (X, Y) plane
        (``x_axis`` samples local column 1, ``y_axis`` samples local column 2).
    k : scalar or array_like
        Vacuum wavenumber, ``2*pi/wavelength``, in m^-1. If array-like, it
        must have one value per ray.
    delta, beta : scalar or array_like
        Refractive index decrement and absorption index per ray, with
        ``n = 1 - delta + 1j * beta``. If array-like, they must have one value
        per ray.
    flag_lost_value : float, optional
        Negative Shadow4 flag assigned to rays newly lost by this element.
    apply_to_lost : bool, optional
        If True, apply kicks, OPD, phase and attenuation to all stored rays
        with valid thickness support, including rays already marked lost
        with a negative Shadow4 flag. Their existing negative flags are
        preserved. If False, already-lost rays are left unchanged.
    duplicate : bool, optional
        If True, operate on a duplicate of ``beam``. If False, modify ``beam``
        in place.

    Returns
    -------
    shadow4.beam.s4_beam.S4Beam
        Beam with columns 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17 and 18
        updated as needed. Columns 1, 2 and 3 are left untouched.

    Notes
    -----
    The complex field factor is

    ``exp(-k * beta * t) * exp(-1j * k * delta * t)``.

    Therefore the relative OPD added to column 13 is ``-delta * t`` and the
    phase added to columns 14 and 15 is ``-k * delta * t``.

    The angular kick is the thin-phase gradient, applied to the local
    transverse direction components:

    ``dVx = -delta * dt/dx`` and ``dVy = -delta * dt/dy``.

    The local "depth" direction component (Vz, column 6) is recomputed to
    preserve a unit direction vector, keeping the sign of the incoming ray
    (rays reaching the element travel in -Z).

    Shadow4 lost-ray flags are used throughout: column 10 > 0 means alive,
    column 10 < 0 means lost. This function does not use the barc4beams
    ``0 = alive, 1 = lost`` convention. Rays that are already lost are still
    propagated through the phase-deflection calculation when they land on
    valid thickness support if ``apply_to_lost`` is True; their negative
    flag is preserved.
    """
    if flag_lost_value >= 0.0:
        raise ValueError("flag_lost_value must be negative for Shadow4 beams.")

    profile, x_axis, y_axis = _validate_thickness_map(thickness)

    out = beam.duplicate() if duplicate else beam
    rays = out.rays
    n_rays = rays.shape[0]

    k_ray = _as_ray_array("k", k, n_rays)
    delta_ray = _as_ray_array("delta", delta, n_rays)
    beta_ray = _as_ray_array("beta", beta, n_rays)

    valid_support = numpy.isfinite(profile) & (profile >= 0.0)
    if not numpy.any(valid_support):
        raise ValueError("No valid thickness support remains after masking.")

    thickness_map = numpy.where(valid_support, profile, numpy.nan)
    dt_dy, dt_dx = numpy.gradient(thickness_map, y_axis, x_axis)

    x_ray = rays[:, 0]
    y_ray = rays[:, 1]

    thickness_ray = _interp2d_regular(x_axis, y_axis, thickness_map, x_ray, y_ray)
    dt_dx_ray = _interp2d_regular(x_axis, y_axis, dt_dx, x_ray, y_ray)
    dt_dy_ray = _interp2d_regular(x_axis, y_axis, dt_dy, x_ray, y_ray)

    inside = (
        (x_ray >= min(x_axis[0], x_axis[-1]))
        & (x_ray <= max(x_axis[0], x_axis[-1]))
        & (y_ray >= min(y_axis[0], y_axis[-1]))
        & (y_ray <= max(y_axis[0], y_axis[-1]))
    )

    phase = -k_ray * delta_ray * thickness_ray
    opd = -delta_ray * thickness_ray
    amplitude = numpy.exp(-k_ray * beta_ray * thickness_ray)

    kick_x = -delta_ray * dt_dx_ray
    kick_y = -delta_ray * dt_dy_ray

    vx = rays[:, 3].copy()
    vy = rays[:, 4].copy()
    vz = rays[:, 5].copy()

    vx_new = vx + kick_x
    vy_new = vy + kick_y
    vz2_new = 1.0 - vx_new * vx_new - vy_new * vy_new

    valid_through_element = (
        inside
        & numpy.isfinite(thickness_ray)
        & numpy.isfinite(dt_dx_ray)
        & numpy.isfinite(dt_dy_ray)
        & numpy.isfinite(k_ray)
        & (k_ray > 0.0)
        & numpy.isfinite(delta_ray)
        & numpy.isfinite(beta_ray)
        & (beta_ray >= 0.0)
        & numpy.isfinite(phase)
        & numpy.isfinite(opd)
        & numpy.isfinite(amplitude)
        & (amplitude > 0.0)
        & numpy.isfinite(vx_new)
        & numpy.isfinite(vy_new)
        & (vz2_new >= 0.0)
    )

    alive_in = rays[:, 9] > 0.0
    rays_to_apply = numpy.ones(n_rays, dtype=bool) if apply_to_lost else alive_in
    valid = rays_to_apply & valid_through_element
    newly_lost = alive_in & ~valid_through_element
    invalid = rays_to_apply & ~valid_through_element

    sign_vz = numpy.where(vz >= 0.0, 1.0, -1.0)
    vz_new = sign_vz * numpy.sqrt(numpy.maximum(vz2_new, 0.0))

    rays[valid, 3] = vx_new[valid]
    rays[valid, 4] = vy_new[valid]
    rays[valid, 5] = vz_new[valid]

    rays[valid, 12] += opd[valid]
    rays[valid, 13] += phase[valid]
    rays[valid, 14] += phase[valid]

    for column_index in (6, 7, 8, 15, 16, 17):
        rays[valid, column_index] *= amplitude[valid]
        rays[invalid, column_index] = 0.0

    rays[newly_lost, 9] = flag_lost_value

    return out


def _validate_thickness_map(thickness: dict):
    """
    Validate and unpack a regular thin-element thickness map.

    Parameters
    ----------
    thickness : dict
        Dictionary with keys ``"profile"``, ``"x_axis"`` and ``"y_axis"``.
        ``profile`` must be a 2D array with shape ``(ny, nx)`` in metres.
        The axes must be finite, one-dimensional and strictly monotonic.

    Returns
    -------
    profile, x_axis, y_axis
        NumPy arrays containing the validated thickness profile and axes.

    Raises
    ------
    KeyError
        If one of the required keys is missing.
    ValueError
        If the profile shape, axis dimensions, monotonicity or finite-value
        requirements are not satisfied.
    """
    for key in ("profile", "x_axis", "y_axis"):
        if key not in thickness:
            raise KeyError(f"thickness missing key: {key!r}")

    profile = numpy.asarray(thickness["profile"], dtype=float)
    x_axis = numpy.asarray(thickness["x_axis"], dtype=float)
    y_axis = numpy.asarray(thickness["y_axis"], dtype=float)

    if profile.ndim != 2:
        raise ValueError("thickness['profile'] must be 2D with shape (ny, nx).")
    if x_axis.ndim != 1 or y_axis.ndim != 1:
        raise ValueError("thickness['x_axis'] and thickness['y_axis'] must be 1D arrays.")
    if x_axis.size != profile.shape[1] or y_axis.size != profile.shape[0]:
        raise ValueError("Axis lengths must match thickness profile shape (ny, nx).")
    if x_axis.size < 2 or y_axis.size < 2:
        raise ValueError("thickness axes must contain at least two points.")
    if numpy.any(~numpy.isfinite(x_axis)) or numpy.any(~numpy.isfinite(y_axis)):
        raise ValueError("thickness axes must contain finite values.")
    if not (numpy.all(numpy.diff(x_axis) > 0.0) or numpy.all(numpy.diff(x_axis) < 0.0)):
        raise ValueError("thickness['x_axis'] must be strictly monotonic.")
    if not (numpy.all(numpy.diff(y_axis) > 0.0) or numpy.all(numpy.diff(y_axis) < 0.0)):
        raise ValueError("thickness['y_axis'] must be strictly monotonic.")
    if numpy.any(profile[numpy.isfinite(profile)] < 0.0):
        raise ValueError("thickness['profile'] must be non-negative where finite.")

    return profile, x_axis, y_axis


def _as_ray_array(name: str, values, n_rays: int):
    """
    Convert a scalar or per-ray value sequence to a ray-aligned array.

    Parameters
    ----------
    name : str
        Name used in validation error messages.
    values : scalar or array_like
        Scalar value broadcast to all rays, or one-dimensional array with one
        value per ray.
    n_rays : int
        Number of rays expected in the output array.

    Returns
    -------
    numpy.ndarray
        One-dimensional float array with length ``n_rays``.

    Raises
    ------
    ValueError
        If ``values`` is not scalar or one-dimensional, or if its length does
        not match ``n_rays``.
    """
    arr = numpy.asarray(values, dtype=float)
    if arr.ndim == 0:
        return numpy.full(n_rays, float(arr), dtype=float)
    if arr.ndim != 1:
        raise ValueError(f"{name!r} must be scalar or a 1D array.")
    if arr.size != n_rays:
        raise ValueError(f"{name!r} must have length equal to the number of rays ({n_rays}).")
    return arr


def _interp2d_regular(x_axis, y_axis, values, xs, ys):
    """
    Bilinearly interpolate values on a regular rectilinear grid.

    Parameters
    ----------
    x_axis, y_axis : array_like
        One-dimensional grid axes. Either increasing or decreasing order is
        accepted.
    values : array_like
        2D array with shape ``(len(y_axis), len(x_axis))``.
    xs, ys : array_like
        Query coordinates in the same units as ``x_axis`` and ``y_axis``.

    Returns
    -------
    numpy.ndarray
        Interpolated values at ``(xs, ys)``. Points outside the grid, or cells
        touching non-finite corner values, are returned as ``nan``.

    Raises
    ------
    ValueError
        If ``values`` does not have shape ``(len(y_axis), len(x_axis))``.
    """
    x_axis = numpy.asarray(x_axis, dtype=float)
    y_axis = numpy.asarray(y_axis, dtype=float)
    values = numpy.asarray(values, dtype=float)
    xs = numpy.asarray(xs, dtype=float)
    ys = numpy.asarray(ys, dtype=float)

    if values.shape != (y_axis.size, x_axis.size):
        raise ValueError("values shape must be (len(y_axis), len(x_axis)).")

    if x_axis[0] > x_axis[-1]:
        x_axis = x_axis[::-1]
        values = values[:, ::-1]
    if y_axis[0] > y_axis[-1]:
        y_axis = y_axis[::-1]
        values = values[::-1, :]

    ix1 = numpy.searchsorted(x_axis, xs, side="right")
    iy1 = numpy.searchsorted(y_axis, ys, side="right")

    ix1 = numpy.clip(ix1, 1, x_axis.size - 1)
    iy1 = numpy.clip(iy1, 1, y_axis.size - 1)

    ix0 = ix1 - 1
    iy0 = iy1 - 1

    x0 = x_axis[ix0]
    x1 = x_axis[ix1]
    y0 = y_axis[iy0]
    y1 = y_axis[iy1]

    tx = (xs - x0) / (x1 - x0)
    ty = (ys - y0) / (y1 - y0)

    v00 = values[iy0, ix0]
    v10 = values[iy0, ix1]
    v01 = values[iy1, ix0]
    v11 = values[iy1, ix1]

    out = (
        (1.0 - tx) * (1.0 - ty) * v00
        + tx * (1.0 - ty) * v10
        + (1.0 - tx) * ty * v01
        + tx * ty * v11
    )

    bad = (
        (xs < x_axis[0])
        | (xs > x_axis[-1])
        | (ys < y_axis[0])
        | (ys > y_axis[-1])
        | ~numpy.isfinite(v00)
        | ~numpy.isfinite(v10)
        | ~numpy.isfinite(v01)
        | ~numpy.isfinite(v11)
    )
    out[bad] = numpy.nan
    return out


if __name__ == "__main__":
    i = S4PhaseDeflector()
    print(i.get_info())
    print(i.get_surface_shape())
